### PR TITLE
Apply series options to corresponding errors

### PR DESCRIPTION
**Pull request by 153957**
Give error bars the same style as series data.

This at least gives them the same color, but may cause problems if you use for instance dashed lines..

Please review carefully before merging.

### CODE REVIEW

**Comment by 153957** [comment]
@davidfokkema any ideas on this?
Perhaps add additional argument to plotting; `errorstyle`?

**Comment by davidfokkema** [comment]
Maybe ``errorstyle`` *is* better. It is a bit more work, though. My personal preference is to use color, or shades of color, to distinguish between datasets. In that case, giving error bars the same style as the data is *exactly* what I want. Did you encounter a situation in which you wanted to separate the two? Why not implement this as is, and introduce ``errorstyle`` only when needed?

**Comment by davidfokkema** [comment]
Any further thoughts on this?

**Comment by 153957** [comment]
This currently does not work for scatter plots, the markstyle is not passed to style the errors.

**Comment by 153957** [comment]
Also; I agree with your preferences that almost always the errors and data points/line should have the same color. But as noted, this is more difficult for scatter plots, since it hides lines by default and the markstyle is packed in a `mark options` group..

**Comment by 153957** [comment]
This is not the best solution.

**Pull request closed without merging**
