### PR TITLE
Add Travis CI

### PR DESCRIPTION
**Pull request by 153957**
To more easily keep track of compatibility with Python 2.7.x and 3.x as proposed in #13 we could use Travis CI to see if the demo files properly compile on both versions.

This will not work because:
- [ ] matplotlib is not installed but required for one of the demo’s
- [ ] the master does not support Python 3 yet (see xgarrido fork)
- [ ] numpy (unless pre installed) will be compiled during installation, should probably use conda

### CODE REVIEW

**Comment by 153957** [comment]
Hmm.. not very easy to setup up. Travis uses an older version of Ubuntu (12.04 LTS) which by default instealls TeXLive 2009, which is to old, it does not include a recent enough version of PGF.
Moreover, it is also very slow to build on Travis, because it needs to install TeXLive, which takes several minutes. I tried a faster install method, but apt get still wants to install a bunch of packages when installing dvipng and latexmk. Most of those are probably not required, yet some stuff is still missing..

My tests can be seen here: https://travis-ci.org/153957/artist/builds

**Comment by davidfokkema** [comment]
Do we need to actually compile the TeX output? If we write comprehensive (acceptance) tests, we can check the `save()` output, without needing to check PDF output. For Python 2.x and 3.x, the output should be identical, I guess?

**Comment by davidfokkema** [comment]
You can install TeX Live using a scripted installer. TeX Live has been out of date on Debian(-derived) systems for years. See http://tug.org/texlive/acquire-netinstall.html for instructions on installing the latest version. However, this probably takes a *lot* of time.

**Comment by 153957** [comment]
Yes, installing it like that is to slow. For some discussion about LaTeX on Travis see https://github.com/travis-ci/travis-ci/issues/1235

We do not necessarily have to compile the TeX, tests might suffice, but it is a nice check to see if it produces compilable code. Perhaps `lacheck` and `ChkTeX` can be used to check the output, if they work without installing the entire texlive.

**Comment by davidfokkema** [comment]
Interesting link. Not very encouraging. A possible problem I see with installing TeX Live with the official install script or the install script for Ubuntu referenced in the ticket, is that it may install the latest versions of all packages, not the 'fronzen' ones. If that's the case, a build might fail for no other reason than a bug or incompatible change in a LaTeX package.

**Comment by 153957** [comment]
Perhaps this helps:
https://github.com/travis-ci/apt-package-whitelist/commit/043f5373bf60075399d6e2ca5cce317a3599d5a1
But maybe still the old version of TeX.

**Comment by davidfokkema** [comment]
Ouch. From what I can tell it's version 2009.

**Comment by davidfokkema** [comment]
I have enabled Travis builds.

**Comment by 153957** [comment]
For now this is unpractical, maybe we can check again later..

**Pull request closed without merging**
